# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  backend

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 4
    Runtime: nodejs16.x
    Architectures:
      - x86_64
    MemorySize: 256
    Layers:
      - Ref: CommonLayer
  Api:
    OpenApiVersion: 3.0.0
    Cors:
      AllowMethods: "'GET'"
      AllowOrigin: "'*'"

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/common
      CompatibleRuntimes:
        - nodejs16.x


  # API
  WebEndpoint:
    Type: AWS::Serverless::Api
    Properties:
      Name: Anonymoose-Test-API
      EndpointConfiguration:
        Type: EDGE
      StageName: Test
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api.yaml


  # IAM
  APIGatewayInvokeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: ApiGateway
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - '*'


  # Lambda Functions
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Retrieves all users
      FunctionName: Anonymoose-Test-getUsers
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      CodeUri: src/app/user
      Handler: app.getUsers
      Environment:
        Variables:
          TABLE_USER: !Ref UserTable

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Retrieve a user
      FunctionName: Anonymoose-Test-getUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      CodeUri: src/app/user
      Handler: app.getUser
      Environment:
        Variables:
          TABLE_USER: !Ref UserTable

  PostUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create a new user
      FunctionName: Anonymoose-Test-postUser
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      CodeUri: src/app/user
      Handler: app.postUser
      Environment:
        Variables:
          TABLE_USER: !Ref UserTable

  PostUserPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Edit a user's password
      FunctionName: Anonymoose-Test-postUserPassword
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      CodeUri: src/app/user
      Handler: password.postUserPassword
      Environment:
        Variables:
          TABLE_USER: !Ref UserTable

  PostUserResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Ask Change password
      FunctionName: Anonymoose-Test-postUserResetPassword
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      CodeUri: src/app/user
      Handler: password.postUserResetPassword
      Environment:
        Variables:
          TABLE_USER: !Ref UserTable

  PostResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Ask to Reset password
      FunctionName: Anonymoose-Test-postResetPassword
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      CodeUri: src/app/user
      Handler: password.postResetPassword
      Environment:
        Variables:
          TABLE_USER: !Ref UserTable


  # Simple syntax to create a DynamoDB table with a single attribute primary key, more in
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: User
      BillingMode: PAY_PER_REQUEST


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Test stage"
    Value: !Sub "https://${WebEndpoint}.execute-api.${AWS::Region}.amazonaws.com/Test/"
